### ISSUE TITLE
Error Downloading Videos from YouTube

### ISSUE THREAD

**Issue by bcook128** [Unrud/video-downloader#307]
This problem just started with VideoDownloader Flatpak version 0.12.18

I now get an error when downloading videos

Download failed
Details:
ERROR: Error opening output files: Encoder not found

**Comment by kbenweg** [comment]
Same error after the latest update

**Comment by Mumrik93** [comment]
Same here, I also tried installing it as a system package but I receive the same error when installing it that way (on Linux Mint).

**Comment by bcook128** [comment]
Tried deleting the flatpak and reinstalled. New install gave error about yt-dlt not allowing urls by default so I think it was built incorrectly. 

Downgraded to commit 71ac568ef39e7c3d773980e353d7b0aeaaae94ce3c388da0ac50e466ec2999f9 and it's working fine.

**Comment by Hallimax** [comment]
Same problem here with Flatpak version 0.12.18. Installed same version with Snap works fine for me. Maybe something is broken with the Flatpak version...

**Comment by Murray-Dawson** [comment]
Same for me (Flatpak version 0.12.18, fresh install, MPEG opion selected, Linux Mint) - a few downloads work, but most throw the encoder error when assembling the folder of builder files into a single video file. Even with the error, you can go into the assembly folder and use the largest file (the MPEG) OK, but if you only use that (and delete the rest) you will lose the captioning. Otherwise, this program is fantastic!

**Comment by Murray-Dawson** [comment]
There was an update in the software manager today which seems to have fixed the issue (at least for the two downloads I tried). Awesome work!

**Comment by Hallimax** [comment]
Fantastic! This update today has fixed the problem I described! Great work - thank you very much!

**Comment by Unrud** [comment]
Fixed 7774720089e7712cfe85e72b2931f80cd54c2fb4
