### ISSUE TITLE
Notify The User After Download Completes

### ISSUE THREAD

**Issue by ProfessorCode212** [Unrud/video-downloader#83]
I'd like to make a feature request to display a notification once a download finishes. Oftentimes, I am doing something else while downloading a couple of videos. It would help to know when a download completes at those times instead of having to constantly keep an eye on the _VideoDownloader_ window.

**Comment by Unrud** [comment]
We use [G_APPLICATION_NON_UNIQUE](https://developer.gnome.org/gio/stable/GApplication.html#G-APPLICATION-NON-UNIQUE:CAPS) to allow multiple instances (without having a primary instance). Unfortunately this is incompatible with [GNotification](https://developer.gnome.org/gio/stable/GNotification.html). We can show notifications but can't react to user actions (like clicking on the notification) because it is communicated to the primary instance (which we do not have) vie DBus.
To get his working probably I think we need to restructure the program to only have a single instance with multiple windows instead of multiple instances with a single window each.
